dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements/dev.txt
script:
  # Run linters
  - mypy -m vat_validator
  - flake8 vat_validator tests
  # Run tests

  - python setup.py test
  - coverage run --source=vat_validator setup.py test
  - coveralls
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true