dist: xenial
language: python
matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
install:
  - pip install tox coveralls
script:
  - tox
  # Run test coverage
  - coverage run --source=vat_validator setup.py test
  - coveralls
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true