dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install setuptools wheel flake8 mypy sphinx sphinx_rtd_theme
script:
  # Run linters
  - mypy -m vatval
  - flake8 vatval tests
  # Run tests
  - python -m unittest
deploy:
  provider: pypi
  server: https://test.pypi.org/
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    master